=== PHPSC/phpsc-conf/lib/Lcobucci/ActionMapper2/Config/schema/routing.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://lcobucci.com/action-mapper/schema"
	xmlns="http://lcobucci.com/action-mapper/schema"
	elementFormDefault="qualified">
	
	<xs:element name="routing" type="routesConfig" />
	
	<xs:complexType name="routesConfig">
		<xs:sequence>
			<xs:element name="definitionBaseClass" type="classType" minOccurs="0" />
			<xs:element name="routes" type="routesContainer" minOccurs="1" />
			<xs:element name="filters" type="filtersContainer" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="routesContainer">
		<xs:sequence>
			<xs:element name="route" type="routeType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="routeType">
		<xs:attribute name="pattern" type="patternType" use="required" />
		<xs:attribute name="class" type="classType" use="required" />
		<xs:attribute name="method" type="methodType" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="filtersContainer">
		<xs:sequence>
			<xs:element name="filter" type="filterType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="filterType">
		<xs:attribute name="pattern" type="patternType" use="required" />
		<xs:attribute name="class" type="classType" use="required" />
		<xs:attribute name="before" type="xs:boolean" use="optional" default="true" />
	</xs:complexType>
	
	<xs:simpleType name="patternType">
		<xs:restriction base="xs:string">
			<xs:pattern value="/(([a-zA-Z0-9\-_\*%\.]{1,})?/?)*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="classType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(\\?[A-Z]([a-zA-Z0-9_]{1,})?)*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="methodType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(_\*)?([a-z][a-zA-Z0-9_]{1,})?" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== PHPSC/phpsc-conf/config/routes.xml
<?xml version="1.0" encoding="UTF-8"?>
<routing xmlns="http://lcobucci.com/action-mapper/schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://lcobucci.com/action-mapper/schema ../vendor/lcobucci/action-mapper/src/Lcobucci/ActionMapper2/Config/schema/routing.xsd ">
	<routes>
		<route pattern="/*" class="\PHPSC\Conference\Application\Action\Home" />
		<route pattern="/contact/*" class="\PHPSC\Conference\Application\Action\Contact" />
		<route pattern="/oauth" class="\PHPSC\Conference\Application\Action\OAuth" method="choose" />
		<route pattern="/oauth/(provider)/*" class="\PHPSC\Conference\Application\Action\OAuth" />
		<route pattern="/user/*" class="\PHPSC\Conference\Application\Action\User" />
		<route pattern="/call4papers/*" class="\PHPSC\Conference\Application\Action\Call4Papers" />
		<route pattern="/payment/*" class="\PHPSC\Conference\Application\Action\Payment" />
		<route pattern="/registration/*" class="\PHPSC\Conference\Application\Action\Registration" />
		<route pattern="/talks/*" class="\PHPSC\Conference\Application\Action\Talks" />
		<route pattern="/status" class="\PHPSC\Conference\Application\Action\Status" />
		<route pattern="/logoff" class="\PHPSC\Conference\Application\Action\Logoff" />
		<route pattern="/companies/*" class="\PHPSC\Conference\Application\Action\Companies" />
		<route pattern="/adm/supporters" class="\PHPSC\Conference\Application\Action\Admin\Supporters" />
		<route pattern="/supporters/*" class="\PHPSC\Conference\Application\Action\Supporters" />
		<route pattern="/supporter/(id)" class="\PHPSC\Conference\Application\Action\Supporter" />
	</routes>
	<filters>
		<filter pattern="/user/*" class="\PHPSC\Conference\Application\Filter\UserFilter" />
		<filter pattern="/call4papers/submissions/new" class="\PHPSC\Conference\Application\Filter\NewTalkFilter" />
		<filter pattern="/call4papers/submissions" class="\PHPSC\Conference\Application\Filter\NewTalkFilter" />
		<filter pattern="/call4papers/feedback" class="\PHPSC\Conference\Application\Filter\CommunityFeedbackFilter" />
		<filter pattern="/registration/new" class="\PHPSC\Conference\Application\Filter\NewAttendeeFilter" />
		<filter pattern="/registration/registered" class="\PHPSC\Conference\Application\Filter\NewAttendeeFilter" />
		<filter pattern="/adm/*" class="\PHPSC\Conference\Application\Filter\AdministratorFilter" />
		<filter pattern="/supporters" class="\PHPSC\Conference\Application\Filter\ApiManagementFilter" httpMethods="POST" />
	</filters>
</routing>
